name: cleavage_prediction
channels:
  - huggingface
  - pytorch
  - conda-forge
  - fastchan
  - defaults
dependencies:
  - blas=1.0=mkl
  - cudatoolkit=11.3.1
  - dataclasses=0.8
  - huggingface_hub=0.9.0
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl_fft
  - mkl_random=1.2.2
  - nltk=3.7
  - numpy-base=1.21.5
  - python=3.10.4
  - pytorch=1.11.0
  - pytorch-mutex=1.0=cuda
  - seaborn=0.11.2
  - torchdata=0.3.0
  - tqdm=4.63.0
  - transformers=4.11.3
  - pip:
    - cython==0.29.28
    - datasets==2.1.0
    - fair-esm==1.0.0
    - fairscale==0.4.8
    - ipykernel==6.9.1
    - ipython==8.2.0
    - jedi==0.18.1
    - matplotlib==3.5.1
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - multiprocess==0.70.12.2
    - mypy-extensions==0.4.3
    - nest-asyncio==1.5.5
    - numpy==1.21.5
    - pandas==1.4.1
    - pillow==9.0.1
    - pip==21.2.4
    - ray==1.13.0
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - tokenizers==0.10.3
    - torch==1.11.0
    - torchaudio==0.11.0
    - torchsummary==1.5.1
    - torchtext==0.12.0
    - torchvision==0.12.0
